### PR TITLE
Daragh branch 1 a scene builder

### PR DESCRIPTION
**Pull request by SabiKov**
I try to re-merge into a master branch

### CODE REVIEW

**Comment by daraghwalshe** [comment]
We can Allways rollback. The scene on my local is still good too.


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Szabolcs Kovacs <notifications@github.com> </div><div>Date:2015/10/09  3:18 PM  (GMT-07:00) </div><div>To: SabiKov/HumanEvolution <HumanEvolution@noreply.github.com> </div><div>Subject: [HumanEvolution] Daragh branch 1 a scene builder (#10) </div><div>
</div>I try to re-merge into a master branch

You can view, comment on, or merge this pull request online at:

  https://github.com/SabiKov/HumanEvolution/pull/10

Commit Summary

deleted scene 1 and scene 4a
Merge pull request #9 from SabiKov/master
File Changes

R Assets/New Terrain.asset.meta~HEAD.meta (4)
M Assets/Prefabs/SK_River.prefab.meta (2)
M Assets/Prefabs/SK_WoodenLog.prefab.meta (2)
A Assets/Prefabs/river.prefab.meta (8)
A Assets/Prefabs/stone_cube.prefab.meta (8)
A Assets/Prefabs/woodenLog.prefab.meta (8)
D Assets/Scenes/scene10.unity (673)
D Assets/Scenes/scene_1.unity (2618)
M Assets/Scenes/scene_1_sk.unity.meta (2)  
M Assets/Scenes/scene_4.unity (0)
D Assets/Scenes/scene_4_a.unity (0)
M Assets/Standard Assets/Characters/FirstPersonCharacter/Prefabs/FPSController.prefab (0)
M Assets/Standard Assets/Effects/GlassRefraction/Materials/GlassRefractive.mat (0)
M Assets/Standard Assets/Environment/Water/Water/Materials/WaterProNighttime.mat (0)   
M Assets/Standard Assets/Environment/Water/Water4/Materials/Water4Advanced.mat (0)
M Assets/Standard Assets/Environment/Water/Water4/Materials/Water4Simple.mat (0)
M Assets/Streets/Materials/Crossing.mat (0)   
M Assets/Streets/Materials/Sidewalk.mat (0)
M Assets/Streets/Materials/Street-T.mat (0)  
M Assets/Streets/Materials/Street-X.mat (0)  
M Assets/Streets/Materials/Street.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/S_G_000105_F.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/S_G_000163_S.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/S_G_000177_E.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/S_G_000181_E.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/S_RiverSideWall.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_build_A.mat     (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_build_A2.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_build_A3.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_build_A4.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_build_A5.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_build_A6.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_building_B - Copy.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_building_B.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_building_C - Copy.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_building_D 2.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_building_D.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_building___X.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_building_base.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/dw_building_base_2.mat (0)
M Assets/ZRNAssets/005339_08932_25_14/Materials/materials/stone.mat (0)
M Assets/dw_working_assets/dw_errie_skybox.mat (0)
A Assets/materials.meta (9)
M Assets/prefabs/Building_Prefabs/dw_building_2.prefab (0)
M Assets/prefabs/Building_Prefabs/dw_building_2a.prefab (0)
M Assets/prefabs/Building_Prefabs/dw_building_3.prefab (0)
M Assets/prefabs/Building_Prefabs/dw_building_4.prefab (0)
M Assets/prefabs/Building_Prefabs/dw_building_5.prefab (0)
M Assets/prefabs/Building_Prefabs/dw_building_6.prefab (0)
M Assets/prefabs/Building_Prefabs/dw_building_7.prefab (0)
M Assets/prefabs/Building_Prefabs/dw_building_7a.prefab (0)
M Assets/prefabs/Building_Prefabs/dw_building_8.prefab (0)
M Assets/prefabs/Building_Prefabs/dw_building_base.prefab (0)
M Assets/prefabs/Building_Prefabs/dw_building_base2.prefab     (0)
M Assets/prefabs/DW_CarSpawnCapsule.prefab (0)
M Assets/prefabs/DW_Car_North.prefab (0)
M Assets/prefabs/dw_brick_wall.prefab (0)
M ProjectSettings/QualitySettings.asset (0)
M ProjectSettings/TagManager.asset (0)
Patch Links:

https://github.com/SabiKov/HumanEvolution/pull/10.patch
https://github.com/SabiKov/HumanEvolution/pull/10.diff

**Comment by SabiKov** [comment]
Ok. we have 16 heads far from the tail. I don't know exactly which one was good for everyone. By the way I tried to rollback back but merge conflict issues were in unity's .metas, which means modification happened on the same lines from both source so I have to make a decision which one stay or not. this definitely will cause some broken effect on scene.

**Comment by SabiKov** [comment]
I'm trying to update your branch but this happens see below on snapshot
screenshot 2015-10-10 01 21 29

**Comment by SabiKov** [comment]
screenshot 2015-10-10 01 25 40

**Comment by SabiKov** [comment]
The git forces me to add these modifications to the staging area(delete all building assets) otherwise I can't merge into the master. That's why we had broken scene because some assets were removed. I think so, it will be the same if I merge again.

**Comment by daraghwalshe** [comment]
Hi Sabi
I'm looking at this too.
Im pretty sure its the file structure.
My local repo has your and my scenes working perfect. Daves is really messed up though:
image

One thing I did notice in a good few of the later commits from today , 
(I downloaded them as zip files so as not to interfere with my local repo) is this 
There are TWO prefab folders. 
HumanEvolution\Assets\prefabs
HumanEvolution\Assets\Prefabs
WinRar was giving a warning 
"The following file already exists
HumanEvolution-bbedbbcf722a5a4b8ff12d045e4c224ab33a8193\Assets\prefabs.meta"

There is defo something wrong with that because you cannot have two files with the same name in the same directory. I'm guessing that we need to make sure there are no folder names almost alike before a merge such as  prefabs and Prefabs.
Im hoping this is the case anyway, because it will be an easy fix, after all the hours spent looking at it that is.

**Comment by SabiKov** [comment]
So we had duplicated file structure, my unity was crashed. I was searching hours how to get back the proper version without loosing anything, however, the best appropriate solution was to move back until stable version of master. I did it, but your scene gone. After that, I tried to re-merge your sub-branch into the current master but I couldn't because branch has conflicts now.

**Pull request merged**
